// <auto-generated />
using System;
using ChatBot.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatBot.Data.Migrations
{
    [DbContext(typeof(ChatBotContext))]
    [Migration("20220702201004_PhotoLogicUpdate")]
    partial class PhotoLogicUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChatBot.Data.DTL.ClothType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClothTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hat"
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.ColorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Transparent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AliceBlue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AntiqueWhite"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aqua"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aquamarine"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bisque"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 10,
                            Name = "BlanchedAlmond"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 12,
                            Name = "BlueViolet"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 14,
                            Name = "BurlyWood"
                        },
                        new
                        {
                            Id = 15,
                            Name = "CadetBlue"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chartreuse"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Coral"
                        },
                        new
                        {
                            Id = 19,
                            Name = "CornflowerBlue"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cornsilk"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Crimson"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cyan"
                        },
                        new
                        {
                            Id = 23,
                            Name = "DarkBlue"
                        },
                        new
                        {
                            Id = 24,
                            Name = "DarkCyan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "DarkGoldenrod"
                        },
                        new
                        {
                            Id = 26,
                            Name = "DarkGray"
                        },
                        new
                        {
                            Id = 27,
                            Name = "DarkGreen"
                        },
                        new
                        {
                            Id = 28,
                            Name = "DarkKhaki"
                        },
                        new
                        {
                            Id = 29,
                            Name = "DarkMagenta"
                        },
                        new
                        {
                            Id = 30,
                            Name = "DarkOliveGreen"
                        },
                        new
                        {
                            Id = 31,
                            Name = "DarkOrange"
                        },
                        new
                        {
                            Id = 32,
                            Name = "DarkOrchid"
                        },
                        new
                        {
                            Id = 33,
                            Name = "DarkRed"
                        },
                        new
                        {
                            Id = 34,
                            Name = "DarkSalmon"
                        },
                        new
                        {
                            Id = 35,
                            Name = "DarkSeaGreen"
                        },
                        new
                        {
                            Id = 36,
                            Name = "DarkSlateBlue"
                        },
                        new
                        {
                            Id = 37,
                            Name = "DarkSlateGray"
                        },
                        new
                        {
                            Id = 38,
                            Name = "DarkTurquoise"
                        },
                        new
                        {
                            Id = 39,
                            Name = "DarkViolet"
                        },
                        new
                        {
                            Id = 40,
                            Name = "DeepPink"
                        },
                        new
                        {
                            Id = 41,
                            Name = "DeepSkyBlue"
                        },
                        new
                        {
                            Id = 42,
                            Name = "DimGray"
                        },
                        new
                        {
                            Id = 43,
                            Name = "DodgerBlue"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Firebrick"
                        },
                        new
                        {
                            Id = 45,
                            Name = "FloralWhite"
                        },
                        new
                        {
                            Id = 46,
                            Name = "ForestGreen"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Fuchsia"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Gainsboro"
                        },
                        new
                        {
                            Id = 49,
                            Name = "GhostWhite"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Goldenrod"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 54,
                            Name = "GreenYellow"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Honeydew"
                        },
                        new
                        {
                            Id = 56,
                            Name = "HotPink"
                        },
                        new
                        {
                            Id = 57,
                            Name = "IndianRed"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Indigo"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Ivory"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Khaki"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Lavender"
                        },
                        new
                        {
                            Id = 62,
                            Name = "LavenderBlush"
                        },
                        new
                        {
                            Id = 63,
                            Name = "LawnGreen"
                        },
                        new
                        {
                            Id = 64,
                            Name = "LemonChiffon"
                        },
                        new
                        {
                            Id = 65,
                            Name = "LightBlue"
                        },
                        new
                        {
                            Id = 66,
                            Name = "LightCoral"
                        },
                        new
                        {
                            Id = 67,
                            Name = "LightCyan"
                        },
                        new
                        {
                            Id = 68,
                            Name = "LightGoldenrodYellow"
                        },
                        new
                        {
                            Id = 69,
                            Name = "LightGray"
                        },
                        new
                        {
                            Id = 70,
                            Name = "LightGreen"
                        },
                        new
                        {
                            Id = 71,
                            Name = "LightPink"
                        },
                        new
                        {
                            Id = 72,
                            Name = "LightSalmon"
                        },
                        new
                        {
                            Id = 73,
                            Name = "LightSeaGreen"
                        },
                        new
                        {
                            Id = 74,
                            Name = "LightSkyBlue"
                        },
                        new
                        {
                            Id = 75,
                            Name = "LightSlateGray"
                        },
                        new
                        {
                            Id = 76,
                            Name = "LightSteelBlue"
                        },
                        new
                        {
                            Id = 77,
                            Name = "LightYellow"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 79,
                            Name = "LimeGreen"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Linen"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Magenta"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Maroon"
                        },
                        new
                        {
                            Id = 83,
                            Name = "MediumAquamarine"
                        },
                        new
                        {
                            Id = 84,
                            Name = "MediumBlue"
                        },
                        new
                        {
                            Id = 85,
                            Name = "MediumOrchid"
                        },
                        new
                        {
                            Id = 86,
                            Name = "MediumPurple"
                        },
                        new
                        {
                            Id = 87,
                            Name = "MediumSeaGreen"
                        },
                        new
                        {
                            Id = 88,
                            Name = "MediumSlateBlue"
                        },
                        new
                        {
                            Id = 89,
                            Name = "MediumSpringGreen"
                        },
                        new
                        {
                            Id = 90,
                            Name = "MediumTurquoise"
                        },
                        new
                        {
                            Id = 91,
                            Name = "MediumVioletRed"
                        },
                        new
                        {
                            Id = 92,
                            Name = "MidnightBlue"
                        },
                        new
                        {
                            Id = 93,
                            Name = "MintCream"
                        },
                        new
                        {
                            Id = 94,
                            Name = "MistyRose"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Moccasin"
                        },
                        new
                        {
                            Id = 96,
                            Name = "NavajoWhite"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 98,
                            Name = "OldLace"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 100,
                            Name = "OliveDrab"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 102,
                            Name = "OrangeRed"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Orchid"
                        },
                        new
                        {
                            Id = 104,
                            Name = "PaleGoldenrod"
                        },
                        new
                        {
                            Id = 105,
                            Name = "PaleGreen"
                        },
                        new
                        {
                            Id = 106,
                            Name = "PaleTurquoise"
                        },
                        new
                        {
                            Id = 107,
                            Name = "PaleVioletRed"
                        },
                        new
                        {
                            Id = 108,
                            Name = "PapayaWhip"
                        },
                        new
                        {
                            Id = 109,
                            Name = "PeachPuff"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Plum"
                        },
                        new
                        {
                            Id = 113,
                            Name = "PowderBlue"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 116,
                            Name = "RosyBrown"
                        },
                        new
                        {
                            Id = 117,
                            Name = "RoyalBlue"
                        },
                        new
                        {
                            Id = 118,
                            Name = "SaddleBrown"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 120,
                            Name = "SandyBrown"
                        },
                        new
                        {
                            Id = 121,
                            Name = "SeaGreen"
                        },
                        new
                        {
                            Id = 122,
                            Name = "SeaShell"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Sienna"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 125,
                            Name = "SkyBlue"
                        },
                        new
                        {
                            Id = 126,
                            Name = "SlateBlue"
                        },
                        new
                        {
                            Id = 127,
                            Name = "SlateGray"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Snow"
                        },
                        new
                        {
                            Id = 129,
                            Name = "SpringGreen"
                        },
                        new
                        {
                            Id = 130,
                            Name = "SteelBlue"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Tan"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Teal"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Thistle"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Turquoise"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Violet"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 138,
                            Name = "White"
                        },
                        new
                        {
                            Id = 139,
                            Name = "WhiteSmoke"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 141,
                            Name = "YellowGreen"
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leather"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Silk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kashmir"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wool"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Synthetics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Satin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Linen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lace"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Denim"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Crepe"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chiffon"
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClothTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeEuTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SizeUsTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClothTypeId");

                    b.HasIndex("ColorTypeId");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("SizeEuTypeId");

                    b.HasIndex("SizeUsTypeId");

                    b.HasIndex("UserCartId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClothTypeId = 1,
                            ColorTypeId = 9,
                            Description = "ყველაზე მაგარი ბრენდული შარვალი",
                            MaterialTypeId = 2,
                            Name = "მასიმო დუტის შარვალი",
                            Price = 399.99000000000001,
                            SizeEuTypeId = 39,
                            SizeUsTypeId = 38
                        },
                        new
                        {
                            Id = 2,
                            ClothTypeId = 2,
                            ColorTypeId = 46,
                            Description = "ყველაზე ძერსკი კაბა",
                            MaterialTypeId = 4,
                            Name = "ზარას კაბა",
                            Price = 899.99000000000001,
                            SizeEuTypeId = 36,
                            SizeUsTypeId = 36
                        },
                        new
                        {
                            Id = 3,
                            ClothTypeId = 3,
                            ColorTypeId = 120,
                            Description = "ყველაზე ხარისხიანი კეტები",
                            MaterialTypeId = 1,
                            Name = "Eco კეტები",
                            Price = 299.99000000000001,
                            SizeEuTypeId = 43,
                            SizeUsTypeId = 42
                        },
                        new
                        {
                            Id = 4,
                            ClothTypeId = 4,
                            ColorTypeId = 107,
                            Description = "ყველაზე ლამაზი ქუდი",
                            MaterialTypeId = 7,
                            Name = "ლუი ვიტონის ქუდი",
                            Price = 99.989999999999995,
                            SizeEuTypeId = 40,
                            SizeUsTypeId = 40
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.SizeEuType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SizeEuTypes");

                    b.HasData(
                        new
                        {
                            Id = 32,
                            Value = 32
                        },
                        new
                        {
                            Id = 33,
                            Value = 33
                        },
                        new
                        {
                            Id = 34,
                            Value = 34
                        },
                        new
                        {
                            Id = 35,
                            Value = 35
                        },
                        new
                        {
                            Id = 36,
                            Value = 36
                        },
                        new
                        {
                            Id = 37,
                            Value = 37
                        },
                        new
                        {
                            Id = 38,
                            Value = 38
                        },
                        new
                        {
                            Id = 39,
                            Value = 39
                        },
                        new
                        {
                            Id = 40,
                            Value = 40
                        },
                        new
                        {
                            Id = 41,
                            Value = 41
                        },
                        new
                        {
                            Id = 42,
                            Value = 42
                        },
                        new
                        {
                            Id = 43,
                            Value = 43
                        },
                        new
                        {
                            Id = 44,
                            Value = 44
                        },
                        new
                        {
                            Id = 45,
                            Value = 45
                        },
                        new
                        {
                            Id = 46,
                            Value = 46
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.SizeUsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SizeUsTypes");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            Value = "Xs"
                        },
                        new
                        {
                            Id = 36,
                            Value = "S"
                        },
                        new
                        {
                            Id = 38,
                            Value = "M"
                        },
                        new
                        {
                            Id = 40,
                            Value = "L"
                        },
                        new
                        {
                            Id = 42,
                            Value = "Xl"
                        },
                        new
                        {
                            Id = 44,
                            Value = "XXl"
                        },
                        new
                        {
                            Id = 46,
                            Value = "XXXl"
                        });
                });

            modelBuilder.Entity("ChatBot.Data.DTL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChatBot.Data.DTL.UserCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCarts");
                });

            modelBuilder.Entity("ChatBot.Data.DTL.Product", b =>
                {
                    b.HasOne("ChatBot.Data.DTL.ClothType", "ClothType")
                        .WithMany()
                        .HasForeignKey("ClothTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBot.Data.DTL.ColorType", "ColorType")
                        .WithMany()
                        .HasForeignKey("ColorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBot.Data.DTL.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBot.Data.DTL.SizeEuType", "SizeEuType")
                        .WithMany()
                        .HasForeignKey("SizeEuTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBot.Data.DTL.SizeUsType", "SizeUsType")
                        .WithMany()
                        .HasForeignKey("SizeUsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatBot.Data.DTL.UserCart", "UserCart")
                        .WithMany("Product")
                        .HasForeignKey("UserCartId");

                    b.Navigation("ClothType");

                    b.Navigation("ColorType");

                    b.Navigation("MaterialType");

                    b.Navigation("SizeEuType");

                    b.Navigation("SizeUsType");

                    b.Navigation("UserCart");
                });

            modelBuilder.Entity("ChatBot.Data.DTL.UserCart", b =>
                {
                    b.HasOne("ChatBot.Data.DTL.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatBot.Data.DTL.UserCart", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
